spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 174555679353-5jm75nei77b6kptg8dep7d8jnofmd445.apps.googleusercontent.com
            clientSecret: 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



server:
  port: 9081
